service: chargingbreak-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  stackName: chargingbreak-${self:provider.stage}
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    CHARGERS_TABLE: chargers
    TIPS_TABLE: tips
    TIP_VOTES_TABLE: tip_votes
    RATINGS_TABLE: ratings
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:provider.environment.CHARGERS_TABLE}"
        - "arn:aws:dynamodb:*:*:table/${self:provider.environment.TIPS_TABLE}"
        - "arn:aws:dynamodb:*:*:table/${self:provider.environment.TIP_VOTES_TABLE}"
        - "arn:aws:dynamodb:*:*:table/${self:provider.environment.RATINGS_TABLE}"
        
custom:
  defaultStage: ${git:branch}
  customDomain:
    domainName: api.chargingbreak.com
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    
plugins:
  - serverless-plugin-git-variables
  - serverless-domain-manager

functions:
  - ${file(resources/functions/charger.yml)}
  - ${file(resources/functions/adminUpdateChargers.yml)}
  - ${file(resources/functions/search.yml)}
  - ${file(resources/functions/tip.yml)}
  
resources:
  - ${file(resources/tables/chargers.yml)}
  - ${file(resources/tables/tips.yml)}
  - ${file(resources/tables/tip_votes.yml)}
  - ${file(resources/tables/ratings.yml)}
  - ${file(resources/CBUser.yml)}
  - ${file(resources/CognitoAuthorizer.yml)}
