service: chargingbreak-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  stackName: chargingbreak-${self:provider.stage}
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    SUPERCHARGERINFO_TABLE: SuperchargerInfo
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.SUPERCHARGERINFO_TABLE}"
        
custom:
  defaultStage: ${git:branch}
  customDomain:
    domainName: api.chargingbreak.com
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    
plugins:
  - serverless-plugin-git-variables
  - serverless-domain-manager

functions:
  - ${file(resources/functions/charger.yml)}
  - ${file(resources/functions/adminUpdateChargers.yml)}
  - ${file(resources/functions/search.yml)}
  
resources:
  - ${file(resources/tables/SuperchargeInfo.yml)}
  - ${file(resources/CBUser.yml)}
